### ISSUE TITLE
known issue: logging into server requires several attempts sometimes

### ISSUE THREAD

**Issue by DoomSquirter** [Beyond-Reality/Beyond-Realty-Farscapes#13]
no error, just login/logout in quick succession, sometimes twice, sometimes many more times till you finally are able to login.

Not tied to tps.  having issues with nobody on server and tps at 20.

**Comment by tworf** [comment]
Seems to be caused by not enough potions all the time. 

`23:00:32] [Netty Client IO #6/ERROR] [FML]: There was a critical exception handling a packet on channel nep
[16/6/2017 23:00:32 PM] java.util.ConcurrentModificationException
[16/6/2017 23:00:32 PM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_91]
[16/6/2017 23:00:32 PM] 	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_91]
[16/6/2017 23:00:32 PM] 	at com.tmtravlr.nep.recipes.NEPRecipes.removeAddedShapelessCrafting(NEPRecipes.java:165) ~[NEPRecipes.class:?]
[16/6/2017 23:00:32 PM] 	at com.tmtravlr.nep.config.ConfigVanillaCrafting.loadShapelessRecipes(ConfigVanillaCrafting.java:312) ~[ConfigVanillaCrafting.class:?]`

**Comment by leagris** [comment]
Seems to be fixed since 1.0.7-r3
