### ISSUE TITLE
Quark sort button results in "fatal error conenction terminated"

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/Beyond-Realty-Farscapes#16]
pressing the quark sort button seems to diconenct me from the server with a fatal error. 

`[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/ERROR] [FML]: SimpleChannelHandlerWrapper exception
[13/6/2017 13:11:35 PM] java.util.ConcurrentModificationException
[13/6/2017 13:11:35 PM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_91]
[13/6/2017 13:11:35 PM] 	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_91]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.recipes.NEPRecipes.removeAddedShapelessCrafting(NEPRecipes.java:165) ~[NEPRecipes.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.config.ConfigVanillaCrafting.loadShapelessRecipes(ConfigVanillaCrafting.java:312) ~[ConfigVanillaCrafting.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.network.PacketHandlerClient.onMessage(PacketHandlerClient.java:129) ~[PacketHandlerClient.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.network.PacketHandlerClient.onMessage(PacketHandlerClient.java:26) ~[PacketHandlerClient.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:102) [FMLProxyPacket.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [er.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [er.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at ic2.core.network.RpcHandler.channelRead0(RpcHandler.java:123) [RpcHandler.class:?]
[13/6/2017 13:11:35 PM] 	at ic2.core.network.RpcHandler.channelRead0(RpcHandler.java:25) [RpcHandler.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:410) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:275) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/ERROR] [FML]: There was a critical exception handling a packet on channel nep
[13/6/2017 13:11:35 PM] java.util.ConcurrentModificationException
[13/6/2017 13:11:35 PM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_91]
[13/6/2017 13:11:35 PM] 	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_91]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.recipes.NEPRecipes.removeAddedShapelessCrafting(NEPRecipes.java:165) ~[NEPRecipes.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.config.ConfigVanillaCrafting.loadShapelessRecipes(ConfigVanillaCrafting.java:312) ~[ConfigVanillaCrafting.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.network.PacketHandlerClient.onMessage(PacketHandlerClient.java:129) ~[PacketHandlerClient.class:?]
[13/6/2017 13:11:35 PM] 	at com.tmtravlr.nep.network.PacketHandlerClient.onMessage(PacketHandlerClient.java:26) ~[PacketHandlerClient.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[DefaultChannelPipeline.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:102) [FMLProxyPacket.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [er.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [er.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at ic2.core.network.RpcHandler.channelRead0(RpcHandler.java:123) [RpcHandler.class:?]
[13/6/2017 13:11:35 PM] 	at ic2.core.network.RpcHandler.channelRead0(RpcHandler.java:25) [RpcHandler.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:410) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:275) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
[13/6/2017 13:11:35 PM] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/INFO] [Galacticraft]: Unregistered Dimension: -30
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/INFO] [Galacticraft]: Unregistered Dimension: -29
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/INFO] [Galacticraft]: Unregistered Dimension: -31
[13/6/2017 13:11:35 PM] [13:11:35] [Netty Client IO #7/INFO] [Galacticraft]: Unregistered Dimension: -28
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: Loading scripts
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading beyondrealitycore.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading rtfm.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading ic2.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading industrialforegoing.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading actuallyadditions.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading biomesoplenty.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading intermod
[13/6/2017 13:11:35 PM] [Client thread/INFO]: [STDOUT]: MineTweaker: Loading missing_pieces.zs
[13/6/2017 13:11:35 PM] [Client thread/INFO] [FTBLib]: Reloaded CLIENT on packmode 'default'
[13/6/2017 13:11:35 PM] [Client thread/INFO] [Actually Additions]: Created temporary WorldData to cache data on the client!
[13/6/2017 13:11:35 PM] [Client thread/INFO] [Actually Additions]: Receiving (new or changed) Player Data for player **MINECRAFTUSERNAME**.
[13/6/2017 13:11:35 PM] [13:11:35] [Thread-22/ERROR]: Error in class 'SourceLWJGL OpenAL'
[13/6/2017 13:11:35 PM] [13:11:35] [Thread-22/ERROR]: Channel null in method 'stop'
[13/6/2017 13:11:35 PM] [13:11:35] [Thread-22/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[13/6/2017 13:11:35 PM] [13:11:35] [Thread-22/ERROR]: Source '20ee6635-4914-439a-a9fc-7daa68807aab' not found in method 'play'
[13/6/2017 13:11:36 PM] [Client thread/INFO] [FML]: Applying holder lookups
[13/6/2017 13:11:36 PM] [Client thread/INFO] [FML]: Holder lookups applied
[13/6/2017 13:11:43 PM] [Client thread/INFO] [Actually Additions]: Unloaded WorldData!`

**Comment by leagris** [comment]
Hopefully this Quark update fixes this kind of issue: https://minecraft.curseforge.com/projects/quark/files/2433183
