### ISSUE TITLE
Crash with the random inventory Notch / Trollface

### ISSUE THREAD

**Issue by tworf** [Beyond-Reality/Beyond-Realty-Farscapes#24]
I had a seemingly random crash looking at the crashlog it looks like it's trying to load the trollface from imgur but from an incorrect url... "http://www:http://i.imgur.com/XXHNN4F.png"

`
Time: 6/18/17 10:33 PM
Description: Registering texture

java.lang.NullPointerException: Registering texture
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42)
	at code.elix_x.excore.client.thingy.ThingyDisplay$MovingHuman.drawGuiPost(ThingyDisplay.java:216)
	at code.elix_x.excore.client.thingy.ThingyDisplay.draw(ThingyDisplay.java:134)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1433_ThingyDisplay_draw_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:383)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: http://www:http://i.imgur.com/XXHNN4F.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture`

Full crash file below

[crash-2017-06-18_22.33.30-client.txt](https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/files/1083401/crash-2017-06-18_22.33.30-client.txt)

**Comment by leagris** [comment]
Forgotten broken unsed dependency
Safe to delete `mods/1.11.2/EXCore-2.0.0-alpha10-1.11.2.jar`
I remove it for next update

**Comment by leagris** [comment]
Fixed in current release
